# Colorscheme
include ./themes/dracula.conf

# Font
font_size 16.0

font_family      Iosevka Term Extended
bold_font        Iosevka Term Extended Bold
italic_font      Iosevka Term Extended Italic
bold_italic_font Iosevka Term Extended Bold Italic

# Colorscheme
background_opacity 0.6
background_blur 25

# Mac OS specific
macos_option_as_alt yes
macos_hide_from_tasks yes
macos_quit_when_last_window_closed no
macos_traditional_fullscreen no
macos_colorspace displayp3

# Cursor
cursor cyan
cursor_trail 5
cursor_trail_decay 0.1 0.4
cursor_trail_color cyan

# Monitor
repaint_delay 8
sync_to_monitor yes

# Windows
hide_window_decorations titlebar-only

# Tabs
tab_bar_style powerline
tab_powerline_style slanted
tab_title_template "{fmt.fg.tab}[{index}] {title}"
