return {
	{
		"nyoom-engineering/oxocarbon.nvim",
		lazy = true,
	},
	{
		"theamallalgi/zitchdog",
		lazy = true,
	},
	{
		"eldritch-theme/eldritch.nvim",
		lazy = true,
	},
	{
		"maxmx03/fluoromachine.nvim",
		lazy = true,
		config = function()
			require("fluoromachine").setup({
				theme = "retrowave",
				brightness = 0.05,
				glow = true,
				transparent = false,
				styles = {
					comments = {},
					functions = {},
					variables = {},
					numbers = {},
					constants = { bold = true },
					parameters = {},
					keywords = {},
					types = {},
				},
				colors = {},
				overrides = {},
				plugins = {
					bufferline = true,
					cmp = true,
					dashboard = true,
					editor = true,
					gitsign = true,
					hop = true,
					ibl = true,
					illuminate = true,
					lazy = true,
					minicursor = true,
					ministarter = true,
					minitabline = true,
					ministatusline = true,
					navic = true,
					neogit = true,
					neotree = true,
					noice = true,
					notify = true,
					lspconfig = true,
					syntax = true,
					telescope = true,
					treesitter = true,
					tree = true,
					wk = true,
				},
			})
		end,
	},
}
